[package]
name = "my_first_crate_rpn_calc"
version = "0.1.0"
authors = ["John waku Doe"]
description = "A simple RPN calculator"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
